apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
  namespace: {{ .Values.namespace }}
  labels:
    - app: valheim
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: valheim
  template:
    metadata:
      labels:
        app: valheim
    spec:
      containers:
        - name: valheim
          image: {{.Values.image.repository}}:{{.Values.image.tag}}
          args:
            - ./valheim_server.x86_64
            - -name
            - "{{ .Values.serverConfig.name }}"
            - -port
            - "{{ .Values.serverConfig.port }}"
            - -world
            - "{{ .Values.serverConfig.world }}"
            - -password
            - "{{ .Values.serverConfig.password }}"
                 {{- if .Values.serverConfig.crossplay }}
            - -crossplay
                 {{- end }}
          ports:
            - containerPort: {{ .Values.serverConfig.port }}
              name: game
            - containerPort: {{ add .Values.serverConfig.port 1 }}
              name: game-2
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: valheim-data
              mountPath: /config
      volumes:
        - name: valheim-data
          persistentVolumeClaim:
            claimName: {{.Release.Name}}-valheim-pvc
---
# valheim-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name}}-valheim-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
---