apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
        - name: main
          image: {{.Values.image.repository}}:{{.Values.image.tag}}
          ports:
            {{- toYaml .Values.container.port | nindent 12 }}
          envFrom:
            {{- toYaml .Values.container.envFrom | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}