replicaCount: 1
namespace: hearthhub

image:
  repository: cbartram/hearthhub-mod-api
  pullPolicy: IfNotPresent

  # Tag for the API itself
  tag: "0.0.20"

  # Versions for images the API is responsible for deploying
  # i.e. sidecar container, valheim server, and mod/file manager
  valheimImageName: "cbartram/hearthhub"
  valheimImageVersion: "0.0.6"
  backupManagerImageName: "cbartram/hearthhub-sidecar"
  backupManagerImageVersion: "0.0.4"
  fileManagerImageName: "cbartram/hearthhub-plugin-manager"
  fileManagerImageVersion: "0.0.6"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30000

ingress:
  enabled: true
  className: nginx
  serviceName: hearthhub-mod-api
  port: 8080
  host: hearthhub-api.ai

resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

