replicaCount: 1
namespace: hearthhub

image:
  repository: cbartram/hearthhub-mod-api
  pullPolicy: IfNotPresent
  tag: "0.0.3"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 32426

ingress:
  enabled: true
  className: nginx
  serviceName: hearthhub-mod-api-svc
  port: 80
  host: hello-world.example

resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

