name: hearthhub-kube-api
frontendServiceName: hearthhub-frontend-service
namespace: hearthhub
replicaCount: 1

stripe:
  mode: test

s3:
  bucketName: "hearthhub-backups"

db:
  host: "hearthhub-db.hearthhub.svc.cluster.local"

api:
  # Base url for this API used by other services which need to call the API from within the cluster (i.e. file manager job)
  baseUrl: "https://hearthhub.duckdns.org"
  rabbitmqBaseUrl: "rabbitmq.rabbitmq.svc.cluster.local:5672"

image:
  repository: cbartram/hearthhub-mod-api
  pullPolicy: IfNotPresent

  # Tag for the API itself
  tag: "0.0.86"

  # Versions for images the API is responsible for deploying
  # i.e. sidecar container, valheim server, and mod/file manager
  valheimImageName: "cbartram/hearthhub"
  valheimImageVersion: "0.0.10"

  # sidecar / backup manager
  backupManagerImageName: "cbartram/hearthhub-sidecar"
  backupManagerImageVersion: "0.0.39"

  # file manager / plugin manager
  fileManagerImageName: "cbartram/hearthhub-plugin-manager"
  fileManagerImageVersion: "0.0.33"

serviceAccountName: hearthhub-api-sa

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
