name: hearthhub-kube-api
namespace: hearthhub
replicaCount: 1

s3:
  bucketName: "hearthhub-backups"

api:
  # Base url for this API used by other services which need to call the API from within the cluster (i.e. file manager job)
  baseUrl: "http://hearthhub-kube-api.hearthhub.svc.cluster.local:8080"
  rabbitmqBaseUrl: "rabbitmq.rabbitmq.svc.cluster.local:5672"

image:
  repository: cbartram/hearthhub-mod-api
  pullPolicy: IfNotPresent

  # Tag for the API itself
  tag: "0.0.54"

  # Versions for images the API is responsible for deploying
  # i.e. sidecar container, valheim server, and mod/file manager
  valheimImageName: "cbartram/hearthhub"
  valheimImageVersion: "0.0.8"
  backupManagerImageName: "cbartram/hearthhub-sidecar"
  backupManagerImageVersion: "0.0.16"
  fileManagerImageName: "cbartram/hearthhub-plugin-manager"
  fileManagerImageVersion: "0.0.20"

imagePullSecrets: []
serviceAccountName: hearthhub-api-sa

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30000

ingress:
  enabled: true
  className: nginx
  serviceName: hearthhub-kube-api
  port: 8080
  host: hearthhub-api.ai

resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
