apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  namespace: {{.Values.namespace}}
data:
  # Versions and images for containers the API is responsible
  # for deploying
  VALHEIM_IMAGE_NAME: {{.Values.image.valheimImageName | quote }}
  VALHEIM_IMAGE_VERSION: {{.Values.image.valheimImageVersion | quote }}
  BACKUP_MANAGER_IMAGE_NAME: {{ .Values.image.backupManagerImageName | quote }}
  BACKUP_MANAGER_IMAGE_VERSION: {{ .Values.image.backupManagerImageVersion | quote }}
  FILE_MANAGER_IMAGE_NAME: {{ .Values.image.fileManagerImageName | quote }}
  FILE_MANAGER_IMAGE_VERSION:  {{ .Values.image.fileManagerImageVersion | quote }}
  API_VERSION: {{ .Values.image.tag | quote }}

  # API
  AWS_REGION: "us-east-1"
  BUCKET_NAME: {{ .Values.s3.bucketName | quote }}
  API_BASE_URL: {{ .Values.api.baseUrl | quote }}
  RABBITMQ_BASE_URL: {{ .Values.api.rabbitmqBaseUrl | quote }}
  GIN_MODE: "release"

  # Backup manager sidecar
  MAX_BACKUPS: "3"
  BACKUP_FREQUENCY_MIN: "10"
  CLEANUP_FREQUENCY_MIN: "60"

  # Resources for valheim server
  CPU_REQUEST: "2"
  MEMORY_REQUEST: "8Gi"
  CPU_LIMIT: "2"
  MEMORY_LIMIT: "11Gi"
