apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  namespace: {{.Values.namespace}}
data:
  # Versions and images for containers the API is responsible
  # for deploying
  VALHEIM_IMAGE_NAME: {{.Values.image.valheimImageName | quote }}
  VALHEIM_IMAGE_VERSION: {{.Values.image.valheimImageVersion | quote }}
  BACKUP_MANAGER_IMAGE_NAME: {{ .Values.image.backupManagerImageName | quote }}
  BACKUP_MANAGER_IMAGE_VERSION: {{ .Values.image.backupManagerImageVersion | quote }}
  FILE_MANAGER_IMAGE_NAME: {{ .Values.image.fileManagerImageName | quote }}
  FILE_MANAGER_IMAGE_VERSION:  {{ .Values.image.fileManagerImageVersion | quote }}

  AWS_REGION: "us-east-1"
  BUCKET_NAME: {{ .Values.s3.bucketName | quote }}
  API_BASE_URL: {{ .Values.api.baseUrl | quote }}
  GIN_MODE: "release"
  BACKUP_FREQUENCY_MIN: "10"
  CLEANUP_FREQUENCY_MIN: "60"

  # Resources
  CPU_REQUEST: "2"
  MEMORY_REQUEST: "4Gi"
  CPU_LIMIT: "2"
  MEMORY_LIMIT: "6Gi"
