apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.namespace }}
  name: hearthhub-api-role
rules:
  - apiGroups: [""]
    resources:
      - persistentvolumeclaims
      - pods
      - services
    verbs: ["create", "get", "list", "watch", "delete", "update", "patch"]

  - apiGroups: ["apps"]
    resources:
      - deployments
      - deployments/scale
      - replicasets
    verbs: ["create", "get", "list", "watch", "delete", "update", "patch"]
  - apiGroups: ["batch"]
    resources:
        - jobs
    verbs: ["create", "get", "list", "watch", "delete", "update", "patch"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["create", "get", "list", "watch", "delete", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hearthhub-api-role-binding
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: hearthhub-api-sa
    namespace: {{.Values.namespace}}
roleRef:
  kind: Role
  name: hearthhub-api-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hearthhub-api-sa
  namespace: {{ .Values.namespace }}
---