name: rabbitmq
namespace: rabbitmq

replicaCount: 1

image:
  repository: rabbitmq
  pullPolicy: IfNotPresent
  tag: "4.0.5-management"

container:
  port:
    - containerPort: 5672
      name: amqp
    - containerPort: 15672
      name: http
  envFrom:
    - secretRef:
        name: rabbitmq-secrets

service:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: 5672
      name: amqp
    - port: 15672
      targetPort: 15672
      name: http

resources:
   limits:
     cpu: 500m
     memory: 1Gi
   requests:
     cpu: 200m
     memory: 512Mi
